### ISSUE TITLE
A .AeonConfig sample file will be welcome

### ISSUE THREAD

**Issue by elGuille-info** [gregdivis/Aeon#3]
Basically, to know how to set "virtual" disks or how to mount a drive using a local path.
And other usual things.

Looking at the classes AeonConfiguration and AeonDriveConfiguration I can guess, but to be sure :-)

Thanks in advance.
Guillermo

**Comment by gregdivis** [comment]
I'll publish some examples soon. That format started out as xml, then was yaml, and now is finally json. I probably won't change it again... :)

I had planned to add some configuration UI back in too, eventually.

-Greg

**Comment by gregdivis** [comment]
I've added a few basic examples in https://github.com/gregdivis/Aeon/tree/master/examples - I'll document the format more as I get time. Is that enough for now?

**Comment by elGuille-info** [comment]
> I've added a few basic examples in https://github.com/gregdivis/Aeon/tree/master/examples - I'll document the format more as I get time. Is that enough for now?

Yes, thank you! 😃
